#ifndef _SERPENT_H
#define _SERPENT_H

extern gcry_core_cipher_spec_t gcry_core_cipher_serpent128;
extern gcry_core_cipher_spec_t gcry_core_cipher_serpent192;
extern gcry_core_cipher_spec_t gcry_core_cipher_serpent256;

#endif
